wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1744023416
    t:
      1:
      - 1
      - 11
      4: 3.8.5
      5: 0.12.0
      6: 4.33.2
      8:
      - 5
