wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744086789.931522
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      - 105
      2:
      - 1
      - 41
      - 51
      - 55
      - 105
      3:
      - 1
      - 13
      - 23
      4: 3.9.18
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
